### PR TITLE
Add feature/fix bug/Improve something

### PR DESCRIPTION
**Pull request by Arnavpk**

### CODE REVIEW

**Comment by Arnavpk** [comment]
@Mayank77maruti  Chekout the changes

**Comment by Mayank77maruti** [comment]
looks good for laptop view but for mobile view things are not aligned can you try to make the look better in mobile view.

**Comment by Arnavpk** [comment]
> looks good for laptop view but for mobile view things are not aligned can you try to make the look better in mobile Will

okay...i will checkout and make the changes

**Comment by Mayank77maruti** [comment]
Hey @Arnavpk , resolve the conflicts.

**Pull request closed without merging**
